#import "./post.gql"
#import "./comment.gql"
#import "./tag.gql"
#import "./overviewPost.gql"

fragment DetailPost on Post {
  id
  text
  isLiked
  isSubscribed
  ...Post
  comments {
    ...Comment
  }
  tags {
    ...Tag
  }
  relatedSubPosts {
    ...OverviewPost
  }
}
