#import "./fragments/subscription.gql"

mutation CreateSubscription($subscriptionInput: SubscriptionInput!) {
  createSubscription(subscriptionInput: $subscriptionInput) {
    success
    errors
  }
}
