#import "./fragments/overviewPost.gql"

query NotificationPosts($activePage: Int!) {
  paginatedNotificationPosts(activePage: $activePage) {
    posts {
      ...OverviewPost
    }
    numPostPages
  }
}
