#import "./fragments/overviewPost.gql"

mutation UpdatePostStatus($updatePostStatusInput: UpdatePostStatusInput!) {
  updatePostStatus(updatePostStatusInput: $updatePostStatusInput) {
    success
    errors
    post {
      ...OverviewPost
    }
  }
}
